version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HelloWorldStack2022"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1o93dlzuw4yrs"
s3_prefix = "HelloWorldStack2022"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=209409592105.dkr.ecr.us-east-1.amazonaws.com/helloworldstack2022ba9b8e93/helloworldfunction19d43fc4repo"]
